// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "804a9ebf-e34e-4d08-a305-2d216b1d29ca");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1677345821);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1677345957);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1677345972);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1677346104);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1677346002);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{5e8c02a0-792c-40f3-8b71-16635a2a06ed}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1677345790);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{eef563c0-796f-4740-b676-aa071f88abde}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\"],\"idsInUrlbar\":[\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1677345945);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1677345971024");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1677367571024");
user_pref("browser.search.region", "TR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230109134456");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1677346156");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "www.google.com");
user_pref("browser.startup.homepage_override.buildID", "20230109134456");
user_pref("browser.startup.homepage_override.mstone", "102.7.0");
user_pref("browser.startup.lastColdStartupCheck", 1677346156);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1677345953025");
user_pref("distribution.iniFile.exists.appversion", "102.7.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "TR");
user_pref("dom.push.userAgentID", "99f473165de342fbbc48268df22d550c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1677346157);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230109134456");
user_pref("extensions.lastAppVersion", "102.7.0");
user_pref("extensions.lastPlatformVersion", "102.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{036a55b4-5e72-4d05-a06c-cba2dfcc134a}", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f56e5525-4d7e-4371-9740-028053182470\",\"formautofill@mozilla.org\":\"7e373a03-f5b2-4d23-b25f-aca665b1be3e\",\"pictureinpicture@mozilla.org\":\"51109f46-3f73-4830-ab90-a99495bd58c2\",\"screenshots@mozilla.org\":\"e032d282-4bcf-4088-bff2-befa15f93db2\",\"webcompat-reporter@mozilla.org\":\"d6445004-9837-4660-b619-bc1607c37f10\",\"webcompat@mozilla.org\":\"a8a32375-ecf1-4399-aa00-bfe3e1587610\",\"default-theme@mozilla.org\":\"8ec490e9-3bd0-40a9-b39d-d93f373a70b0\",\"addons-search-detection@mozilla.com\":\"e3c2d730-1495-4cf3-afaf-2106b183534e\",\"google@search.mozilla.org\":\"dcf65dac-06fa-4682-856a-730260a81b73\",\"wikipedia@search.mozilla.org\":\"d4acbf33-9b47-4e56-9c08-978e0f589e44\",\"ddg@search.mozilla.org\":\"da480c61-4cca-4335-9a8a-051134346871\",\"{036a55b4-5e72-4d05-a06c-cba2dfcc134a}\":\"a8d83837-869c-4486-a248-1da61d48e4ea\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1677346080);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.disable_button.openCertManager", false);
user_pref("security.sandbox.content.tempDirSuffix", "31699ac2-2df1-4cc7-a0f8-c71c88770ad5");
user_pref("services.settings.blocklists.gfx.last_check", 1677346104);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_update_seconds", 1677346104);
user_pref("services.settings.main.devtools-compatibility-browsers.last_check", 1677346104);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1677346104);
user_pref("services.settings.main.search-config.last_check", 1677346104);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1677346155);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230109134456");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
