// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1672901293);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a5cb2f19-36d6-4561-b838-fc406bbe76cb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "/S92rzfUdA8IqLNkEq93Ow==");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1672901454600");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1672923054600");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "www.google.com.tr");
user_pref("browser.startup.lastColdStartupCheck", 1672901469);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "105.0.2-1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "0b203e6cce42411089e7f493dd42f447");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20221005121034");
user_pref("extensions.lastAppVersion", "105.0.2-1");
user_pref("extensions.lastPlatformVersion", "105.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"559b907d-b524-4591-bcee-185ec21d676f\",\"pictureinpicture@mozilla.org\":\"c4e3feef-c2f2-43e2-9245-244ac2e1ca25\",\"screenshots@mozilla.org\":\"ea701cc7-a043-4472-9a2d-e96e71062bec\",\"webcompat@mozilla.org\":\"48ae2419-23b5-4635-aed4-3dabb0e5d568\",\"default-theme@mozilla.org\":\"a1c6fd02-6c52-44f6-9594-09d49e4f518e\",\"addons-search-detection@mozilla.com\":\"a25cd1cb-f040-41a5-bce3-d49ed16e90f0\",\"wikipedia@search.mozilla.org\":\"8e8893ea-fd19-4682-85be-5c46b6002d39\",\"ddg@search.mozilla.org\":\"e67c2cd9-1cd6-4ad4-898d-5f69310c86c7\",\"uBlock0@raymondhill.net\":\"9bfc6ff4-f742-463e-aa05-3b6a8180c9a2\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1672901462);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.locale.requested", "tr,en-US,en-CA,en-GB");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.spoof_english", 1);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "2197c8a0-f358-4202-adc4-b1904cd9980e");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1672901467);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
