// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "4f679020-c744-4fbd-a1a3-42c824119bc6");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1675593412);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1675593393);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1675593532);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1675593442);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e4a6a2ec-9e80-439d-abc2-32764369f0c5}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1675593382);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e10189e0-52db-4867-a139-ffd51e8483a7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\"],\"idsInUrlbar\":[\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1675593387);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1675593416772");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1675615016772");
user_pref("browser.search.region", "TR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1675593385");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "www.google.com");
user_pref("browser.startup.homepage_override.buildID", "20230112150232");
user_pref("browser.startup.homepage_override.mstone", "109.0");
user_pref("browser.startup.lastColdStartupCheck", 1675593384);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"unified-extensions-area\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1675593390260");
user_pref("distribution.iniFile.exists.appversion", "109.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "TR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "65ca1283f86f4cef82994c01a1ba949c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1675593386);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230112150232");
user_pref("extensions.lastAppVersion", "109.0");
user_pref("extensions.lastPlatformVersion", "109.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{036a55b4-5e72-4d05-a06c-cba2dfcc134a}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"baa30cb8-6be8-49a7-b1bd-ef34ab6d0df3\",\"pictureinpicture@mozilla.org\":\"15383331-f27f-46ed-a4ba-7936a392cdec\",\"screenshots@mozilla.org\":\"7360deca-ee93-4d30-a784-21d298421ef9\",\"webcompat-reporter@mozilla.org\":\"46de7c5c-f4c4-4b66-ae31-0f3812fa1990\",\"webcompat@mozilla.org\":\"95068a4d-f6d6-461e-a492-61b53b1fafec\",\"default-theme@mozilla.org\":\"f53db91a-9fbd-40a4-9430-61a7d3eb7ed4\",\"addons-search-detection@mozilla.com\":\"e0daea97-56fa-45ce-8fa6-a0ed2b3a9d71\",\"google@search.mozilla.org\":\"3e2bfa5b-5a82-45f4-889e-3c870f52963e\",\"wikipedia@search.mozilla.org\":\"9e61f47e-c9e5-4ec5-bed4-934397db324a\",\"ddg@search.mozilla.org\":\"24a00c7f-55c1-43a7-a754-f5241abbf789\",\"{036a55b4-5e72-4d05-a06c-cba2dfcc134a}\":\"78bf012a-a5f6-4a9b-bf58-4eb1cd15eb52\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1675593390);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.disable_button.openCertManager", false);
user_pref("security.sandbox.content.tempDirSuffix", "1858312e-45d3-46c6-a4a7-fc560a67b28e");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1675593377);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230112150232");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
